### ISSUE TITLE
关于IDFB 特征提取的问题

### ISSUE THREAD

**Issue by hubu-wangpei** [zhanghong863/Feature-Extractors-for-Video-Steganalysis#1]
您好，最近拜读了您的文章，在复现实验的时候遇到一个问题，就是使用您这个仓库里的IDFB提取工具，提取出来的特征有多行，应该怎么处理？
比如，我隐写了一个60帧的视频，用您提供的软件提取到的特征文件，一共有43行数据，每行768个浮点数，在您论文里提到的特征为768，这里要求平均得到1*768的特征数据，然后再用集成分类器训练吗？

**Comment by zhanghong863** [comment]
Hi，特征提取文件存在多行是正常现象。您在使用提取器时，设定的"-t"参数值是多少？例如，如果“-t”取值为8，那么每处理8帧就输出一行特征，也即：处理完1-8帧输出一行特征，处理完9-16帧输出下一行特征，以此类推。

**Comment by hubu-wangpei** [comment]
非常感谢您的回复

还有以下几个疑问和请求
1. 在提取器相同压缩包里的readme.txt中写到，-t选项指定的是gop的大小，这个是在隐写嵌入的时候，进行H.264编码时指定的gop大小吗？如果是这样的话， 提取到的多行特征，进一步怎么处理？是求平均值还是什么？如果不是的话，是否设置-t 60（视频原始数据为60帧）来获得1*768维的特征，最终输入到集成分类器中训练。
```
1. Syntax: extractor.exe -s -t gop_size -i infile -o outfile
	-s: turn on the slient mode
```
2.  非常冒昧的请求，您能否提供隐写好的数据集？我使用JM19软件来做隐写嵌入，编码速度非常慢，而且由于本人的编码能力有限，有很多实现不到位的地方。
